[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
solc = "0.8.28" 
optimizer = true
optimizer_runs = 0
evm_version = "cancun" 
gas_reports = ["*"]
bytecode_hash = "none"
fs_permissions = [{ access = "read-write", path = "./" }]
extra_output = ["storageLayout"]
ffi = true
dynamic_test_linking = true

[fuzz]
runs = 10000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
scroll = "${SCROLL_RPC}"
base = "${BASE_RPC}"
optimism = "${OPTIMISM_RPC}"
polygon = "${POLYGON_RPC}"
linea = "${LINEA_RPC}"
sonic = "${SONIC_RPC}"
avalanche = "${AVALANCHE_RPC}"
mantle = "${MANTLE_RPC}"
plasma = "${PLASMA_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
scroll = { key = "${ETHERSCAN_KEY}" }
base = { key = "${ETHERSCAN_KEY}" }
optimism = { key = "${ETHERSCAN_KEY}" }
hyperevm  = { key = "${ETHERSCAN_KEY}", chain = 999 }
polygon = { key = "${ETHERSCAN_KEY}" }
linea = { key = "${ETHERSCAN_KEY}" }
sonic = { key = "${ETHERSCAN_KEY}" }
avalanche = { key = "${SNOWTRACE_KEY}", chain = 43114, url = "https://api.snowtrace.io/api" }
mantle = { key = "${ETHERSCAN_KEY}" }
plasma = { key = "${ETHERSCAN_KEY}", chain = 9745, url = "https://api.etherscan.io/v2/api?chainid=9745" }


[fmt]
line_length = 500
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
sort_imports = true

[lint]
lint_on_build = false
