// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import { console } from "forge-std/console.sol";

import { AcrossSwapModule } from "../../src/across/AcrossSwapModule.sol";
import { EtherFiDataProvider } from "../../src/data-provider/EtherFiDataProvider.sol";
import { DebtManagerAdmin } from "../../src/debt-manager/DebtManagerAdmin.sol";
import { DebtManagerCore } from "../../src/debt-manager/DebtManagerCore.sol";
import { EnsoSwapModule } from "../../src/enso/EnsoSwapModule.sol";
import { CashModuleCore } from "../../src/modules/cash/CashModuleCore.sol";
import { CashModuleSetters } from "../../src/modules/cash/CashModuleSetters.sol";
import { EtherFiLiquidModule } from "../../src/modules/etherfi/EtherFiLiquidModule.sol";
import { EtherFiLiquidModuleWithReferrer } from "../../src/modules/etherfi/EtherFiLiquidModuleWithReferrer.sol";
import { BeHYPEStakeModule } from "../../src/modules/hype/BeHYPEStakeModule.sol";
import { LendGateway } from "../../src/modules/lend-gateway/LendGateway.sol";
import { MidasModule } from "../../src/modules/midas/MidasModule.sol";
import { StargateModule } from "../../src/modules/stargate/StargateModule.sol";
import { PriceProviderV2 } from "../../src/oracle/PriceProviderV2.sol";
import { RoleRegistry } from "../../src/role-registry/RoleRegistry.sol";
import { StockUnwrapper } from "../../src/stock-withdraw/StockUnwrapper.sol";
import { StockWithdrawModule } from "../../src/stock-withdraw/StockWithdrawModule.sol";
import { TradingLens } from "../../src/trading-safe/TradingLens.sol";
import { RoleGatingBatch3Config } from "./RoleGatingBatch3Config.sol";

/// @title DeployRoleGatingBatch3
/// @notice Batch-3 deployments for the role re-gating rollout (PR #289), Optimism or Ethereum:
///         every new implementation plus the five replacement immutable modules on OP. See
///         RoleGatingBatch3Config for the full scope.
///
///         Deployments only — no proxy is upgraded, no role granted, no module registered. That
///         happens in the batch-3 bundles generated by RoleGatingBatch3Cutover.
///
///         Everything deploys through the permissioned EtherFiDeployer (CREATE3, chain-scoped
///         salts), so the script is idempotent: a re-run skips anything already deployed. Each new
///         contract's immutables are read back and required to match the live contract it replaces.
///
/// Usage (Ledger) — pass --sender so simulation and broadcast agree on the account.
/// WARNING: forge 1.6.0-nightly broadcasts even without --broadcast; there is no dry run here.
///   ENV=mainnet forge script scripts/role-gating-batch3/DeployRoleGatingBatch3.s.sol \
///     --rpc-url $OPTIMISM_RPC --ledger --sender <ledger-addr> --broadcast --verify --etherscan-api-key $ETHERSCAN_KEY
///   ENV=mainnet forge script scripts/role-gating-batch3/DeployRoleGatingBatch3.s.sol \
///     --rpc-url $MAINNET_RPC  --ledger --sender <ledger-addr> --broadcast --verify --etherscan-api-key $ETHERSCAN_KEY
contract DeployRoleGatingBatch3 is RoleGatingBatch3Config {
    string constant OUT = "batch3";

    function run() public {
        require(block.chainid == 10 || block.chainid == 1, "DeployRoleGatingBatch3: Optimism or Ethereum only");
        require(isEqualString(getEnv(), "mainnet"), "ENV must be mainnet");
        require(address(DEPLOYER).code.length > 0, "EtherFiDeployer not deployed on this chain");

        vm.startBroadcast();
        {
            (, address broadcaster,) = vm.readCallers();
            require(DEPLOYER.isDeployer(broadcaster), "broadcaster is not in the EtherFiDeployer registry");
        }
        if (block.chainid == 10) _deployOptimism();
        else _deployEthereum();
        vm.stopBroadcast();

        vm.serializeUint(OUT, "block", block.number);
        string memory finalJson = vm.serializeString(OUT, "commit", "PR #289 (stake-1889) + batch 3");
        vm.writeJson(finalJson, _recordPath());

        console.log("=== Batch-3 deployments complete. No state changed on live contracts. ===");
    }

    // ─────────────────────────────── Optimism ───────────────────────────────

    function _deployOptimism() internal {
        OpLive memory l = _readOpLive();
        address dp = l.dataProvider;
        require(address(RoleRegistry(l.roleRegistry).etherFiDataProvider()) == dp, "cash registry: dataProvider mismatch");
        require(_registryIsRegated(l.roleRegistry), "cash RoleRegistry not on re-gated code (batch 1 missing?)");

        // ── cash proxies ──
        address a = _deploy("cashModuleCoreImpl", "CashModuleCoreImpl", abi.encodePacked(type(CashModuleCore).creationCode, abi.encode(dp)));
        require(address(CashModuleCore(payable(a)).etherFiDataProvider()) == dp, "CashModuleCore: dataProvider");
        a = _deploy("cashModuleSettersImpl", "CashModuleSettersImpl", abi.encodePacked(type(CashModuleSetters).creationCode, abi.encode(dp)));
        require(address(CashModuleSetters(payable(a)).etherFiDataProvider()) == dp, "CashModuleSetters: dataProvider");

        a = _deploy("debtManagerCoreImpl", "DebtManagerCoreImpl", abi.encodePacked(type(DebtManagerCore).creationCode, abi.encode(dp)));
        require(address(DebtManagerCore(a).etherFiDataProvider()) == dp, "DebtManagerCore: dataProvider");
        a = _deploy("debtManagerAdminImpl", "DebtManagerAdminImpl", abi.encodePacked(type(DebtManagerAdmin).creationCode, abi.encode(dp)));
        require(address(DebtManagerAdmin(a).etherFiDataProvider()) == dp, "DebtManagerAdmin: dataProvider");

        // No immutables: one impl serves both the cash and the trading EtherFiDataProvider proxies
        _deploy("dataProviderImpl", "EtherFiDataProviderImpl", type(EtherFiDataProvider).creationCode);
        _deploy("priceProviderImpl", "PriceProviderV2Impl", type(PriceProviderV2).creationCode);

        _deploySwapImpls(l.across, l.enso, dp);

        address spoke = address(LendGateway(l.lendGateway).spoke());
        a = _deploy("lendGatewayImpl", "LendGatewayImpl", abi.encodePacked(type(LendGateway).creationCode, abi.encode(dp, spoke)));
        require(address(LendGateway(a).etherFiDataProvider()) == dp && address(LendGateway(a).spoke()) == spoke, "LendGateway: immutables");

        a = _deploy("stockWithdrawModuleImpl", "StockWithdrawModuleImpl", abi.encodePacked(type(StockWithdrawModule).creationCode, abi.encode(dp)));
        require(address(StockWithdrawModule(payable(a)).etherFiDataProvider()) == dp, "StockWithdrawModule: dataProvider");
        require(address(StockWithdrawModule(payable(a)).cashModule()) == address(StockWithdrawModule(payable(l.stockWithdrawModule)).cashModule()), "StockWithdrawModule: cashModule");

        // ── replacement immutable modules ──
        _deployModules(l);

        // ── trading stack ──
        _deployTradingRegistry(l.tradingRoleRegistry, l.tradingDataProvider);
    }

    function _deployModules(OpLive memory l) internal {
        string[5] memory keys = _moduleKeys();
        string[5] memory salts = _moduleSaltNames();
        address dp = l.dataProvider;

        // Liquid + Liquid-with-referrer: tellers from the live module, weth passthrough
        for (uint256 i = 0; i < 2; ++i) {
            EtherFiLiquidModule old = EtherFiLiquidModule(payable(l.oldModules[i]));
            (address[] memory assets, address[] memory tellers) = _liquidConfig(old);
            bytes memory code = i == 0 ? type(EtherFiLiquidModule).creationCode : type(EtherFiLiquidModuleWithReferrer).creationCode;
            address m = _deploy(keys[i], salts[i], abi.encodePacked(code, abi.encode(assets, tellers, dp, old.weth())));
            require(address(EtherFiLiquidModule(payable(m)).etherFiDataProvider()) == dp && EtherFiLiquidModule(payable(m)).weth() == old.weth(), "liquid: immutables");
            for (uint256 k = 0; k < assets.length; ++k) {
                require(address(EtherFiLiquidModule(payable(m)).liquidAssetToTeller(assets[k])) == tellers[k], "liquid: teller not copied");
            }
        }

        {
            StargateModule old = StargateModule(payable(l.oldModules[2]));
            (address[] memory assets, StargateModule.AssetConfig[] memory configs) = _stargateConfig(old);
            address m = _deploy(keys[2], salts[2], abi.encodePacked(type(StargateModule).creationCode, abi.encode(assets, configs, dp)));
            require(address(StargateModule(payable(m)).etherFiDataProvider()) == dp, "stargate: dataProvider");
            for (uint256 k = 0; k < assets.length; ++k) {
                StargateModule.AssetConfig memory c = StargateModule(payable(m)).getAssetConfig(assets[k]);
                require(c.pool == configs[k].pool && c.isOFT == configs[k].isOFT, "stargate: asset config not copied");
            }
        }

        {
            BeHYPEStakeModule old = BeHYPEStakeModule(l.oldModules[3]);
            bytes memory args = abi.encode(dp, address(old.staker()), old.whype(), old.beHYPE(), old.getRefundGasLimit());
            BeHYPEStakeModule m = BeHYPEStakeModule(_deploy(keys[3], salts[3], abi.encodePacked(type(BeHYPEStakeModule).creationCode, args)));
            require(address(m.etherFiDataProvider()) == dp && address(m.staker()) == address(old.staker()), "beHYPE: dataProvider/staker");
            require(m.whype() == old.whype() && m.beHYPE() == old.beHYPE() && m.getRefundGasLimit() == old.getRefundGasLimit(), "beHYPE: config");
        }

        {
            MidasModule old = MidasModule(l.oldModules[4]);
            (address[] memory tokens, address[] memory deposits, address[] memory redemptions) = _midasConfig(old);
            address m = _deploy(keys[4], salts[4], abi.encodePacked(type(MidasModule).creationCode, abi.encode(dp, tokens, deposits, redemptions)));
            require(address(MidasModule(m).etherFiDataProvider()) == dp, "midas: dataProvider");
            for (uint256 k = 0; k < tokens.length; ++k) {
                (address d, address r) = MidasModule(m).vaults(tokens[k]);
                require(d == deposits[k] && r == redemptions[k], "midas: vaults not copied");
            }
        }
    }

    // ─────────────────────────────── Ethereum ───────────────────────────────

    function _deployEthereum() internal {
        EthLive memory l = _readEthLive();
        require(_registryIsRegated(l.roleRegistry), "cash RoleRegistry not on re-gated code (batch 2 missing?)");

        // ── cash stack: StockUnwrapper has no immutables ──
        _deploy("stockUnwrapperImpl", "StockUnwrapperImpl", type(StockUnwrapper).creationCode);

        // ── trading stack ──
        address dp = l.tradingDataProvider;
        _deployTradingRegistry(l.tradingRoleRegistry, dp);
        _deploy("dataProviderImpl", "EtherFiDataProviderImpl", type(EtherFiDataProvider).creationCode);
        _deploy("priceProviderImpl", "PriceProviderV2Impl", type(PriceProviderV2).creationCode);
        _deploySwapImpls(l.across, l.enso, dp);

        address pp = address(TradingLens(l.tradingLens).priceProvider());
        require(pp == l.tradingPriceProvider, "live TradingLens priceProvider != trading PriceProvider");
        address a = _deploy("tradingLensImpl", "TradingLensImpl", abi.encodePacked(type(TradingLens).creationCode, abi.encode(pp)));
        require(address(TradingLens(a).priceProvider()) == pp, "TradingLens: priceProvider");
    }

    // ─────────────────────────────── shared ───────────────────────────────

    /// @dev Across/Enso derive `cashModule` from the data provider at construction (address(0) on the
    ///      ETH trading stack, the real CashModule on OP), so assert against the live impl per chain
    function _deploySwapImpls(address across, address enso, address dp) internal {
        require(address(AcrossSwapModule(payable(across)).etherFiDataProvider()) == dp, "live Across: dataProvider mismatch");
        require(address(EnsoSwapModule(payable(enso)).etherFiDataProvider()) == dp, "live Enso: dataProvider mismatch");

        address a = _deploy("acrossImpl", "AcrossSwapModuleImpl", abi.encodePacked(type(AcrossSwapModule).creationCode, abi.encode(dp)));
        require(address(AcrossSwapModule(payable(a)).etherFiDataProvider()) == dp, "Across: dataProvider");
        require(address(AcrossSwapModule(payable(a)).cashModule()) == address(AcrossSwapModule(payable(across)).cashModule()), "Across: cashModule");

        a = _deploy("ensoImpl", "EnsoSwapModuleImpl", abi.encodePacked(type(EnsoSwapModule).creationCode, abi.encode(dp)));
        require(address(EnsoSwapModule(payable(a)).etherFiDataProvider()) == dp, "Enso: dataProvider");
        require(address(EnsoSwapModule(payable(a)).cashModule()) == address(EnsoSwapModule(payable(enso)).cashModule()), "Enso: cashModule");
    }

    function _deployTradingRegistry(address registry, address dp) internal {
        require(address(RoleRegistry(registry).etherFiDataProvider()) == dp, "live trading registry: dataProvider mismatch");
        address a = _deploy("tradingRoleRegistryImpl", "TradingRoleRegistryImpl", abi.encodePacked(type(RoleRegistry).creationCode, abi.encode(dp)));
        require(address(RoleRegistry(a).etherFiDataProvider()) == dp, "trading registry impl: dataProvider");
    }

    function _deploy(string memory jsonKey, string memory saltName, bytes memory initCode) internal returns (address impl) {
        bytes32 salt = getSalt(_saltName(saltName));
        impl = DEPLOYER.getDeterministicAddress(salt);
        if (impl.code.length > 0) {
            console.log("  [SKIP] already deployed:", jsonKey, impl);
        } else {
            require(DEPLOYER.deploy(salt, initCode) == impl, "deployed != predicted");
            console.log("  [OK]", jsonKey, impl);
        }
        vm.serializeAddress(OUT, jsonKey, impl);
    }
}
