// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import { stdJson } from "forge-std/StdJson.sol";
import { console } from "forge-std/console.sol";

import { RoleRegistry } from "../src/role-registry/RoleRegistry.sol";
import { EtherFiTimelock } from "../src/timelock/EtherFiTimelock.sol";
import { EtherFiDeployer } from "../src/utils/EtherFiDeployer.sol";
import { Utils } from "./utils/Utils.sol";

/// @title DeployTimelock
/// @notice Deploys the EtherFiTimelock on Optimism through the permissioned EtherFiDeployer
///         (CREATE3), with an 8-hour min delay and the cash governance safe as the only
///         proposer, executor and canceller (TimelockController grants CANCELLER_ROLE to
///         proposers in the constructor); no admin, so the timelock administers its own roles
///         behind the delay.
///
///         The EtherFiDeployer lives at the same address on every cash chain and only accounts
///         in its deployer registry can use it, so the salt cannot be squatted and the later
///         multichain rollout with this salt lands the timelock at the same address on every
///         chain. The delay can be raised to its final value through a self-administered
///         `updateDelay` operation without redeploying.
///
///         The script is idempotent: re-running when the timelock already exists skips the
///         deploy and only re-verifies bytecode + configuration.
///
/// @dev This script only deploys the timelock. Transferring RoleRegistry ownership to it is a
///      separate two-step Safe flow generated by scripts/gnosis-txs/TimelockHandoverOptimism.s.sol.
///      The broadcasting account must be in the EtherFiDeployer registry (isDeployer).
///
/// Usage (Ledger) — pass --sender so simulation and broadcast agree on the account:
///   forge script scripts/DeployTimelock.s.sol --rpc-url $OPTIMISM_RPC --ledger --sender <ledger-addr> --broadcast
contract DeployTimelock is Utils {
    /// @dev Permissioned CREATE3 deployer — same address on every cash chain
    EtherFiDeployer constant DEPLOYER = EtherFiDeployer(0xFCD957b5913d607BF2222280093421B1e2Af6f30);

    /// @dev Must stay identical across chains — it alone (with the EtherFiDeployer) determines the address
    bytes32 constant SALT_TIMELOCK = keccak256("DeployTimelock.EtherFiTimelock");

    uint256 constant TIMELOCK_DELAY = 8 hours;

    /// @dev Cash governance multisig owning the RoleRegistry on Optimism
    address constant GOVERNANCE_MULTISIG = 0xA6cf33124cb342D1c604cAC87986B965F428AAC4;

    function run() public {
        require(block.chainid == 10, "DeployTimelock: Optimism only");
        require(address(DEPLOYER).code.length > 0, "EtherFiDeployer not deployed on this chain");

        // ── 1. Resolve governance from the RoleRegistry owner ──
        string memory deployments = readDeploymentFile();
        address roleRegistry = stdJson.readAddress(deployments, string.concat(".", "addresses", ".", "RoleRegistry"));
        address governance = RoleRegistry(roleRegistry).owner();

        // Manual cross-check: the live owner must match the reviewed expectation
        require(governance == GOVERNANCE_MULTISIG, "RoleRegistry owner != expected governance");

        address predicted = DEPLOYER.getDeterministicAddress(SALT_TIMELOCK);

        console.log("=== Deploy EtherFiTimelock (Optimism, 8h delay) ===");
        console.log("Governance (proposer/executor/canceller):", governance);
        console.log("Predicted timelock:", predicted);

        // ── 2. Deploy through the EtherFiDeployer (skipped if already deployed) ──
        address[] memory proposers = new address[](1);
        proposers[0] = governance;

        address[] memory executors = new address[](1);
        executors[0] = governance;

        bytes memory initCode = abi.encodePacked(type(EtherFiTimelock).creationCode, abi.encode(TIMELOCK_DELAY, proposers, executors, address(0)));

        address timelock = predicted;
        address broadcaster = msg.sender;
        if (predicted.code.length > 0) {
            console.log("  [SKIP] already deployed at", predicted);
        } else {
            vm.startBroadcast();
            // msg.sender outside the broadcast context is foundry's default script sender
            // unless --sender is passed; read the account that will actually sign instead
            // of trusting the CLI invocation
            (, broadcaster,) = vm.readCallers();
            require(DEPLOYER.isDeployer(broadcaster), "broadcaster is not in the EtherFiDeployer registry");
            timelock = DEPLOYER.deploy(SALT_TIMELOCK, initCode);
            vm.stopBroadcast();
        }

        require(timelock == predicted, "deployed address != predicted");

        // ── 3. Verify bytecode + configuration ──
        // Requiring an exact runtime-bytecode match against this build guarantees the code at
        // the address is this repo's EtherFiTimelock, whoever deployed it (EtherFiTimelock has
        // no immutables, so type(...).runtimeCode is the exact expected code).
        require(keccak256(timelock.code) == keccak256(type(EtherFiTimelock).runtimeCode), "deployed bytecode != local EtherFiTimelock build");

        EtherFiTimelock tl = EtherFiTimelock(payable(timelock));
        require(tl.getMinDelay() == TIMELOCK_DELAY, "delay != 8 hours");
        require(tl.hasRole(tl.PROPOSER_ROLE(), governance), "governance is not proposer");
        require(tl.hasRole(tl.EXECUTOR_ROLE(), governance), "governance is not executor");
        require(tl.hasRole(tl.CANCELLER_ROLE(), governance), "governance is not canceller");
        require(tl.hasRole(tl.DEFAULT_ADMIN_ROLE(), timelock), "timelock is not its own admin");
        require(!tl.hasRole(tl.DEFAULT_ADMIN_ROLE(), governance), "governance must not be admin");
        require(!tl.hasRole(tl.PROPOSER_ROLE(), broadcaster), "deployer must not be proposer");
        require(!tl.hasRole(tl.EXECUTOR_ROLE(), broadcaster), "deployer must not be executor");
        require(!tl.hasRole(tl.DEFAULT_ADMIN_ROLE(), broadcaster), "deployer must not be admin");

        console.log("  [OK] EtherFiTimelock:", timelock);
        console.log("  [OK] Delay (seconds):", tl.getMinDelay());
    }
}
