// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import { stdJson } from "forge-std/StdJson.sol";
import { console } from "forge-std/console.sol";
import { CREATE3 } from "solady/utils/CREATE3.sol";

import { RoleRegistry } from "../src/role-registry/RoleRegistry.sol";
import { EtherFiTimelock } from "../src/timelock/EtherFiTimelock.sol";
import { Create3Deployer } from "./utils/Create3Deployer.sol";
import { Utils } from "./utils/Utils.sol";

/// @title DeployTimelock
/// @notice Deploys the EtherFiTimelock on Optimism via Nick's factory + CREATE3, with an
///         8-hour min delay and the cash governance safe as the only proposer, executor and
///         canceller (TimelockController grants CANCELLER_ROLE to proposers in the
///         constructor); no admin, so the timelock administers its own roles behind the delay.
///
///         With CREATE3 the address depends only on (factory, salt) — not on initcode or
///         deployer — so the later multichain rollout with this salt lands the timelock at the
///         same address on every cash chain, and the delay can be raised to its final value
///         through a self-administered `updateDelay` operation without redeploying.
///
///         The script is idempotent: re-running when the timelock already exists skips the
///         deploy and only re-verifies the configuration. If the address was squatted through
///         Nick's factory with a different config, verification reverts.
///
/// @dev This script only deploys the timelock. Transferring RoleRegistry ownership to it is a
///      separate two-step Safe flow generated by scripts/gnosis-txs/TimelockHandoverOptimism.s.sol.
///
/// Usage (Ledger). --slow makes forge wait for each receipt before sending the next tx:
/// the CREATE3 proxy must be mined before the creation call that targets it, or that call
/// no-ops against a codeless address and the timelock is never deployed.
///   forge script scripts/DeployTimelock.s.sol --rpc-url $OPTIMISM_RPC --ledger --broadcast --slow
contract DeployTimelock is Utils {
    address constant NICKS_FACTORY = 0x4e59b44847b379578588920cA78FbF26c0B4956C;

    /// @dev Must stay identical across chains — it alone (with the factory) determines the address
    bytes32 constant SALT_TIMELOCK = keccak256("DeployTimelock.EtherFiTimelock");

    uint256 constant TIMELOCK_DELAY = 8 hours;

    /// @dev Cash governance multisig owning the RoleRegistry on Optimism
    address constant GOVERNANCE_MULTISIG = 0xA6cf33124cb342D1c604cAC87986B965F428AAC4;

    function run() public {
        require(block.chainid == 10, "DeployTimelock: Optimism only");
        require(NICKS_FACTORY.code.length > 0, "Nick's factory not deployed on this chain");

        // ── 1. Resolve governance from the RoleRegistry owner ──
        string memory deployments = readDeploymentFile();
        address roleRegistry = stdJson.readAddress(deployments, string.concat(".", "addresses", ".", "RoleRegistry"));
        address governance = RoleRegistry(roleRegistry).owner();

        // Manual cross-check: the live owner must match the reviewed expectation
        require(governance == GOVERNANCE_MULTISIG, "RoleRegistry owner != expected governance");

        address predicted = CREATE3.predictDeterministicAddress(SALT_TIMELOCK, NICKS_FACTORY);

        console.log("=== Deploy EtherFiTimelock (Optimism, 8h delay) ===");
        console.log("Governance (proposer/executor/canceller):", governance);
        console.log("Predicted timelock:", predicted);

        // ── 2. Deploy via Nick's factory + CREATE3 (skipped if already deployed) ──
        address[] memory proposers = new address[](1);
        proposers[0] = governance;

        address[] memory executors = new address[](1);
        executors[0] = governance;

        bytes memory creationCode = abi.encodePacked(type(EtherFiTimelock).creationCode, abi.encode(TIMELOCK_DELAY, proposers, executors, address(0)));

        vm.startBroadcast();
        address timelock = deployCreate3(creationCode, SALT_TIMELOCK);
        vm.stopBroadcast();

        require(timelock == predicted, "deployed address != predicted");

        // ── 3. Verify bytecode + configuration ──
        // The salt is public and Nick's factory permissionless, so an existing deployment could
        // be a mimic squatting the address with the expected view values. Requiring an exact
        // runtime-bytecode match against this build rules that out (EtherFiTimelock has no
        // immutables, so type(...).runtimeCode is the exact expected code).
        require(keccak256(timelock.code) == keccak256(type(EtherFiTimelock).runtimeCode), "deployed bytecode != local EtherFiTimelock build");

        EtherFiTimelock tl = EtherFiTimelock(payable(timelock));
        require(tl.getMinDelay() == TIMELOCK_DELAY, "delay != 8 hours");
        require(tl.hasRole(tl.PROPOSER_ROLE(), governance), "governance is not proposer");
        require(tl.hasRole(tl.EXECUTOR_ROLE(), governance), "governance is not executor");
        require(tl.hasRole(tl.CANCELLER_ROLE(), governance), "governance is not canceller");
        require(tl.hasRole(tl.DEFAULT_ADMIN_ROLE(), timelock), "timelock is not its own admin");
        require(!tl.hasRole(tl.DEFAULT_ADMIN_ROLE(), governance), "governance must not be admin");
        require(!tl.hasRole(tl.PROPOSER_ROLE(), msg.sender), "deployer must not be proposer");
        require(!tl.hasRole(tl.EXECUTOR_ROLE(), msg.sender), "deployer must not be executor");
        require(!tl.hasRole(tl.DEFAULT_ADMIN_ROLE(), msg.sender), "deployer must not be admin");

        console.log("  [OK] EtherFiTimelock:", timelock);
        console.log("  [OK] Delay (seconds):", tl.getMinDelay());
    }

    /// @dev Atomic CREATE3 deployment via Create3Deployer — a single constructor tx that
    ///      reverts on inner-CREATE failure, so gas estimation cannot converge on a limit
    ///      where nothing gets deployed (see Create3Deployer natspec).
    function deployCreate3(bytes memory creationCode, bytes32 salt) internal returns (address deployed) {
        deployed = CREATE3.predictDeterministicAddress(salt, NICKS_FACTORY);

        if (deployed.code.length > 0) {
            console.log("  [SKIP] already deployed at", deployed);
            return deployed;
        }

        new Create3Deployer(creationCode, salt);
        require(deployed.code.length > 0, "CREATE3 deployment verification failed");
    }
}
