name: Test

on:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  ENV: ${{ secrets.ENV || 'mainnet' }}
  TEST_CHAIN: ${{ secrets.TEST_CHAIN || '10' }}
  TEST_RPC: ${{ secrets.TEST_RPC || 'https://mainnet.optimism.io' }}
  MAINNET_RPC: ${{ secrets.MAINNET_RPC }}
  SCROLL_RPC: ${{ secrets.SCROLL_RPC }}
  BASE_RPC: ${{ secrets.BASE_RPC }}
  ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
  HYPEREVM_RPC: ${{ secrets.HYPEREVM_RPC }}
  OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
  OPENOCEAN_API_KEY: ${{ secrets.OPENOCEAN_API_KEY }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge build
        run: forge build --sizes
        id: build

      - name: Run Forge tests
        run: forge test -vvv
        env:
          TS_NODE_COMPILER_OPTIONS: '{"module":"commonjs"}'
        id: test